# Generated by Django 5.2.7 on 2025-10-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_mercadopagoevent_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suscripcionempresa",
            name="annual_price_cents",
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name="suscripcionempresa",
            name="price_cents",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
