# Generated by Django 5.2.7 on 2025-10-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_suscripcionempresa_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcionempresa",
            name="mp_plan_id",
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
