# Generated by Django 5.2.7 on 2025-11-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_suscripcionempresa_mp_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expo_push_token",
            field=models.CharField(
                blank=True,
                help_text="Token de Expo para notificaciones push",
                max_length=255,
                null=True,
            ),
        ),
    ]
