# Generated by Django 5.2.7 on 2025-11-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_expo_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="finalidad",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Seguimiento regular"),
                    ("CORRECTIVA", "Correctiva / desempeño bajo"),
                    ("PROMOCION", "Promoción / mérito"),
                    ("INGRESO", "Ingreso / período de prueba"),
                    ("SALIDA", "Cierre / salida"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
    ]
