# Generated by Django 5.2.6 on 2025-09-22 01:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rut",
            field=models.CharField(
                max_length=12, unique=True, validators=[core.validators.rut_validator]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="segundo_apellido",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
