# Generated by Django 5.2.7 on 2025-10-20 22:31

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MercadoPagoEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tipo", models.CharField(max_length=64)),
                ("data", models.JSONField(default=dict)),
                (
                    "related_preapproval",
                    models.CharField(
                        blank=True, db_index=True, max_length=80, null=True
                    ),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SuscripcionEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("UNICO", "Plan Único")],
                        default="UNICO",
                        max_length=20,
                    ),
                ),
                (
                    "ciclo",
                    models.CharField(
                        choices=[("MENSUAL", "Mensual"), ("ANUAL", "Anual")],
                        default="MENSUAL",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="CLP", max_length=5)),
                ("price_cents", models.PositiveIntegerField(default=19990)),
                ("annual_price_cents", models.PositiveIntegerField(default=204990)),
                (
                    "mp_preapproval_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=80, null=True
                    ),
                ),
                (
                    "mp_payer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INACTIVA", "Inactiva"),
                            ("ACTIVA", "Activa"),
                            ("PAUSADA", "Pausada"),
                            ("CANCELADA", "Cancelada"),
                            ("ERROR", "Error"),
                        ],
                        default="INACTIVA",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("next_billing_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripcion",
                        to="core.empresa",
                    ),
                ),
            ],
        ),
    ]
