# Generated by Django 5.2.6 on 2025-09-23 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_rut_alter_user_segundo_apellido"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREADA", "Creada"),
                            ("ACTUALIZADA", "Actualizada"),
                            ("ELIMINADA", "Eliminada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("campo", models.CharField(blank=True, max_length=50, null=True)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="core.evaluacion",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREADA", "Creada"),
                            ("ACTUALIZADA", "Actualizada"),
                            ("ESTADO", "Cambio de estado"),
                            ("ASIGNACION", "Cambio de asignación"),
                            ("FECHA_LIM", "Cambio de fecha límite"),
                            ("COMENTARIO", "Nuevo comentario"),
                            ("ELIMINADA", "Eliminada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("campo", models.CharField(blank=True, max_length=50, null=True)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "realizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="core.tarea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
