# Generated by Django 5.2.6 on 2025-09-24 07:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_historialevaluacion_historialtarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telefono",
            field=models.CharField(
                blank=True,
                help_text="Formato E.164 (ej: +56912345678)",
                max_length=16,
                null=True,
                validators=[core.validators.validate_e164],
            ),
        ),
    ]
