# Generated by Django 5.2.7 on 2025-10-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_suscripcionempresa_annual_price_cents_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suscripcionempresa",
            options={
                "verbose_name": "Suscripción de Empresa",
                "verbose_name_plural": "Suscripciones de Empresas",
            },
        ),
    ]
