# Generated by Django 5.2.7 on 2025-11-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_evaluacion_finalidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="finalidad",
            field=models.CharField(
                choices=[
                    ("DESEMPENO", "Evaluación de desempeño general"),
                    ("SEGUIMIENTO", "Seguimiento periódico"),
                    ("MEJORA", "Evaluación para mejora o retroalimentación"),
                    ("'INCIDENCIA", "Evaluación por incidencia o bajo rendimiento"),
                    ("PROMOCION", "Evaluación para promoción o reconocimiento"),
                    ("INGRESO", "Ingreso / período de prueba"),
                    ("REORIENTACION", "Reorientación del puesto o funciones"),
                    ("SALIDA", "Evaluación de cierre / salida"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
    ]
