"""
Django settings for pruebatracki project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z2j9r86bo581dw0192ki1tq(a6@(cf5eyt7ax%l_-9=8ocsi8)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

NGROK_DOMAIN = os.environ.get("NGROK_DOMAIN", "").strip()  # ej: https://xxxxx.ngrok-free.dev
NGROK_HOST = NGROK_DOMAIN.replace("https://", "").replace("http://", "")

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    NGROK_HOST,  # dominio ngrok sin https://
]

# Django 4+ necesita esto para cookies/CSRF tras HTTPS externo:
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    NGROK_DOMAIN,  # dominio con https://
]

# Application definition
# Reenvío seguro cuando pasamos por ngrok/proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

INSTALLED_APPS = [
    'admin_interface',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'colorfield',
    'django.contrib.humanize',
    'crispy_forms',
    "crispy_bootstrap5",
    'rest_framework',
]

X_FRAME_OPTIONS='SAMEORIGIN'


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pruebatracki.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "core.context_processors.notifications_context",
            ],
        },
    },
]

WSGI_APPLICATION = "pruebatracki.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGES = [
    ("es", "Español"),
    ("en", "English"),
]


TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
LOGIN_REDIRECT_URL = "/home/"

LOGIN_URL = '/login/'

# Cuando hace logout y vuelve al login
LOGOUT_REDIRECT_URL = '/login/'
# --- SMS Settings (Twilio) ---
SMS_BACKEND = "twilio"  # << activar envío real
TWILIO_ACCOUNT_SID   = "ACb4d8aae8b6551e231a371f7651dc0532"
TWILIO_AUTH_TOKEN    = "bb841b3008c9d7283000aa58ee19005b"
TWILIO_FROM_NUMBER   = "+18254623871"   # tu número de Twilio en formato E.164
# (opcional) si usas Messaging Service:
#TWILIO_MESSAGING_SERVICE_SID = os.getenv("TWILIO_MESSAGING_SERVICE_SID", "")


# === Mercado Pago ===
MERCADOPAGO_ACCESS_TOKEN = os.getenv("MERCADOPAGO_ACCESS_TOKEN", "")
MERCADOPAGO_PUBLIC_KEY = os.getenv("MERCADOPAGO_PUBLIC_KEY", "")
MERCADOPAGO_ENV = os.getenv("MERCADOPAGO_ENV", "test")
MERCADOPAGO_TEST_BUYER_EMAIL = os.getenv("MERCADOPAGO_TEST_BUYER_EMAIL", "")

MERCADOPAGO_SUCCESS_URL = os.getenv(
    "MERCADOPAGO_SUCCESS_URL", "http://127.0.0.1:8000/billing/success/"
)
MERCADOPAGO_FAILURE_URL = os.getenv(
    "MERCADOPAGO_FAILURE_URL", "http://127.0.0.1:8000/billing/failure/"
)
MERCADOPAGO_PENDING_URL = os.getenv(
    "MERCADOPAGO_PENDING_URL", "http://127.0.0.1:8000/billing/pending/"
)
MERCADOPAGO_WEBHOOK_URL = os.getenv(
    "MERCADOPAGO_WEBHOOK_URL", "http://127.0.0.1:8000/webhooks/mercadopago/"
)
MERCADOPAGO_BACK_URL = os.getenv("MERCADOPAGO_BACK_URL", "http://127.0.0.1:8000/")

# === Webhook Secret ===
WEBHOOK_SHARED_SECRET = os.getenv("WEBHOOK_SHARED_SECRET", "")